export const SELECT_USER = "SELECT_USER";
export const CREATE_MENTORSHIP = "CREATE_MENTORSHIP";
export const DELETE_MENTORSHIP = "DELETE_MENTORSHIP";
export const UPDATE_MENTORSHIP = "UPDATE_MENTORSHIP";
export const ADD_RESOURCE_TO_TODO = "ADD_RESOURCE_TO_TODO";
export const REMOVE_TAG_FROM_TODO = "REMOVE_TAG_FROM_TODO";
export const DELETE_TODO = "DELETE_TODO";
